version: '3.4'

services:
  marshmallow.api:
    image: ${DOCKER_REGISTRY-}marshmallowapi
    build:
      context: .
      dockerfile: src/Marshmellow.API/Dockerfile

  marshmallow.producer:
    image: ${DOCKER_REGISTRY-}marshmallowproducer
    build:
      context: .
      dockerfile: src/Marshmallow.Producer/Dockerfile

networks:
  marshmallow-rpc: 
    driver: consumer-network
